name: Release App

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build and Publish Electron App
        run: npm run build:win -w apps/windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
